services:
  - type: web
    name: gestion-vehicules
    env: python
    plan: free
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: gunicorn gestion_vehicules.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: immobilier-vrlf.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
    healthCheckPath: /admin/
    autoDeploy: true
    # Ajouter un volume pour persister la base de donn√©es SQLite
    disk:
      name: database
      mountPath: /opt/render/project/src
      sizeGB: 1
